DROP DATABASE IF EXISTS gmax;

CREATE DATABASE gmax;

USE gmax;

CREATE TABLE User_Profile (

  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  interests VARCHAR(250) NULL,
  photo VARCHAR(200) NULL,
  userRank ENUM NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(250) NULL,
  answerA VARCHAR(50) NULL,
  answerB VARCHAR(50) NULL,
  answerC VARCHAR(50) NULL,
  answerD VARCHAR(50) NULL,
  answerE VARCHAR(50) NULL,
  category ENUM,
  level ENUM,
  correctAnswer ENUM,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);

/* NEED TO VERIFY THIS ONE WITH ZIAD */

CREATE TABLE PERFORMANCE (
  userId INT AUTO_INCREMENT PRIMARY KEY,
  questionId INT,
  correct
);
