DROP DATABASE IF EXISTS gmax;

CREATE DATABASE gmax;

USE gmax;

CREATE TABLE users (

  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  interests VARCHAR(250) NULL,
  admin BOOLEAN NOT NULL DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
 id INT AUTO_INCREMENT PRIMARY KEY,
 userId INT,
 FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
 token VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(2000) NULL,
  answerA VARCHAR(500) NULL,
  answerB VARCHAR(500) NULL,
  answerC VARCHAR(500) NULL,
  answerD VARCHAR(500) NULL,
  answerE VARCHAR(500) NULL,
  categoryId INT,
  FOREIGN KEY (categoryId) REFERENCES category (id) ON DELETE CASCADE,
  level ENUM ('200','300','400') DEFAULT '200',
  correctAnswer ENUM ('A', 'B', 'C', 'D', 'E') NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE category (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  description VARCHAR(100),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY name (name)
);


CREATE TABLE leader_board (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100),
  questionId INT,
  isCorrect BOOLEAN,
  category INT,
  answer ENUM ('A', 'B', 'C', 'D', 'E'),
  level ENUM ('200','300','400'),
  score INT
  time INT

);


ALTER TABLE leader_board ADD COLUMN time INT AFTER score;
